### ISSUE TITLE
coroutine problem with openresty

### ISSUE THREAD

**Issue by DorianGray** [umegaya/ffiex#25]
Is it possible that https://github.com/umegaya/ffiex/blob/f237e848ca75e46558b7806f877d93097ff194da/ffiex/lcpp.lua#L184 can be implemented without coroutines? Is there a specific reason that it's implemented using coroutines?

In the openresty environment, it causes yielding across the c boundary.

**Comment by DorianGray** [comment]
Specifically, using coroutines inside of the cdef callback seems to cause the issue. There doesn't seem to be a way to fix it on the openresty side since for various reasons the coroutine api has been entirely replaced, but I'd really love to continue using this library.

**Comment by umegaya** [comment]
the reason of using coroutine is mainly for developing simplicity. without it, I need to prepare and maintain parsing state machine more strictly. therefore I think its possible to rewrite them with coroutine-free way, but it will take time. 

so I want to take a look openresty code to find the way other than rewrite.
